# Generated by Django 5.1.4 on 2024-12-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('pictures', models.JSONField(default=list)),
                ('description', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('r', 'Reported'), ('c', 'Checked'), ('f', 'Follow-Up')], default='r', max_length=1)),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
        ),
    ]
