# Generated by Django 5.1.4 on 2024-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
